name: Grabit
on:
  push:
    branches:
    - main
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: GOOS=linux go build -o moimhossain .
